version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: postgres:13
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env