# Generated by Django 4.2.7 on 2023-11-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=50)),
                ('preco_ate_cem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_ate_duzentos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_acima_duzentos', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=50)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeria.categoria')),
            ],
        ),
    ]
