# Generated by Django 4.2.7 on 2023-11-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/'),
        ),
    ]
