# Generated by Django 4.2.6 on 2023-11-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_produtos_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='id_categoria',
            new_name='categoria',
        ),
    ]
