# Generated by Django 4.2.6 on 2023-11-03 18:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_rename_id_categoria_produtos_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=150)),
                ('e_mail', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orcamentos',
            fields=[
                ('id_orcamento', models.AutoField(primary_key=True, serialize=False)),
                ('data_orcamento', models.DateField(default=datetime.datetime.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeria.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('data_pedido', models.DateField(default=datetime.datetime.now)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galeria.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='PedidosDetalhes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeria.pedidos')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galeria.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentosDetalhes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeria.orcamentos')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galeria.produtos')),
            ],
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galeria.pedidos'),
        ),
    ]
