# Generated by Django 4.2.6 on 2023-11-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_clientes_orcamentos_pedidos_pedidosdetalhes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='Orcamentos',
            new_name='Orcamento',
        ),
        migrations.RenameModel(
            old_name='OrcamentosDetalhes',
            new_name='OrcamentoDetalhe',
        ),
        migrations.RenameModel(
            old_name='Pedidos',
            new_name='Pedido',
        ),
        migrations.RenameModel(
            old_name='PedidosDetalhes',
            new_name='PedidoDetalhe',
        ),
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
    ]
