# Generated by Django 4.2.6 on 2023-11-03 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_rename_clientes_cliente_rename_orcamentos_orcamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galeria.pedido'),
        ),
    ]
