# Generated by Django 4.2.6 on 2023-11-03 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_orcamento_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentodetalhe',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galeria.produto'),
        ),
        migrations.AlterField(
            model_name='pedidodetalhe',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galeria.produto'),
        ),
    ]
